### ISSUE TITLE
Issue Getting Mod To Work

### ISSUE THREAD

**Issue by DZDiamondGaming** [polusgg/Town-Of-Us#110] opened 2021-04-17 19:41 UTC
I have installed the latest version of this mod however when I go to run the game it doesn't run the mods. I have tried many different methods and still no luck.

I also followed this guide and didn't work.

1. Download the latest TownOfUs Mod zip file from slushiegoose on GitHub.
2. Extract the contents of the zipped folder using a program like WinRar or 7Zip.
3. Locate the root folder for Among Us. The easiest way to find this file path is to open Steam, navigate to Library, right-click Among Us, navigate to Manage, and choose Browse Local Files.
4. Move the extracted mod files into the Among Us root folder. This is the folder containing the Among Us.exe file.
5. Launch Among Us.

If there is an alternate guide then please let me know so I can attempt. I have the latest version installed.

**Comment by arbar5154** [comment] 2021-04-17 20:53
I've noticed that moving the Among Us files from the steam folder first, then copying in the TownOfUs zip contents works. To the point where if someone did it the other way first, they had to delete the folder contents and start again.

**Comment by DZDiamondGaming** [comment] 2021-04-17 22:29
> I've noticed that moving the Among Us files from the steam folder first, then copying in the TownOfUs zip contents works. To the point where if someone did it the other way first, they had to delete the folder contents and start again.

I have tried this about 3 times and still no luck.

**Comment by Eketus** [comment] 2021-04-18 12:20
A friend of mine had the exact same problem. Tried to get it to work multiple times but nothing worked. Then we tried to install another mod called "town of impostors". She got the colors of the mod working, but nothing else seemed to work. So I'm not sure what the problem is. I would really love if someone is able to figure it out.

**Comment by Eketus** [comment] 2021-04-18 18:42
> I have installed the latest version of this mod however when I go to run the game it doesn't run the mods. I have tried many different methods and still no luck.
> 
> I also followed this guide and didn't work.
> 
> 1. Download the latest TownOfUs Mod zip file from slushiegoose on GitHub.
> 2. Extract the contents of the zipped folder using a program like WinRar or 7Zip.
> 3. Locate the root folder for Among Us. The easiest way to find this file path is to open Steam, navigate to Library, right-click Among Us, navigate to Manage, and choose Browse Local Files.
> 4. Move the extracted mod files into the Among Us root folder. This is the folder containing the Among Us.exe file.
> 5. Launch Among Us.
> 
> If there is an alternate guide then please let me know so I can attempt. I have the latest version installed.

My friend got it working. The issue was that she had the original among us on the E disc, while the newly made folder was on the C disc. So she made the new folder on the E disc(where the original among us folder was aswell). And then it worked.

**Comment by amsyarasyiq** [comment] 2021-04-18 22:45
I wanna know if BepInEx has been properly installed to your Among Us' directory by checking if there is LogOutput.log file inside the BepInEx folder.

If it exists, send the LogOutput.log (or it's content) here.

**Comment by uriro726** [comment] 2021-04-22 15:37
> 
> 
> I wanna know if BepInEx has been properly installed to your Among Us' directory by checking if there is LogOutput.log file inside the BepInEx folder.
> 
> If it exists, send the LogOutput.log (or it's content) here.

Hi I'm having the same problem, my mods don't work since the new among us update.
Here is my LogOutput.log file 

[Message: Preloader] BepInEx 6.0.0-reactor.18 - Among Us
[Message: Preloader] BLEEDING EDGE Build #18 from f7d481dda69a6a4964d41d3558a215049e260077 at reactor
[Info   :   BepInEx] System platform: Bits64, Windows
[Info   : Preloader] Running under Unity v2020.2.6.9052483
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:   BepInEx] Chainloader initialized
[Info   :Unhollower] Registered mono type UnhollowerRuntimeLib.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [Reactor 0.3.0-dev]
[Info   :Unhollower] Registered mono type Reactor.Coroutines+Component in il2cpp domain
[Info   :Unhollower] Registered mono type Reactor.ReactorPlugin+ReactorComponent in il2cpp domain
[Info   :   BepInEx] Loading [Town Of Us 2.0.0]
[Error  :   BepInEx] Error loading [Town Of Us 2.0.0] : Method not found: void .ToggleOption.set_LCDAKOCANPH(bool)
[Message:   BepInEx] Chainloader startup complete

Please contact as soon as possible.

**Comment by amsyarasyiq** [comment] 2021-04-22 17:32
latest version of among us won't work with the 2.0.0 TownOfUs update..

update your mod to the latest release

**Comment by amsyarasyiq** [comment] 2021-04-24 11:01
close this issue if it's fixed

**Closed** 2021-06-26 01:18 UTC
