### ISSUE TITLE
'The "GenerateReferences" task failed unexpectedly'

### ISSUE THREAD

**Issue by fatalterreur** [polusgg/Town-Of-Us#101] opened 2021-04-14 06:28 UTC
This issue when i use Dotnet build.

Your .csproj file contain the values for mappings (0.3.0), Among Us (2021.3.31.3), and OxygenFilter (0.3.0). Isn't correct ?
I use your last Reactor.dll updated.

Thanks in advance!

**Comment by MrFawkes1337** [comment] 2021-04-14 10:53
Change Mappings to 0.4.0, and change everything that errors to the new value. OxygenFilter iirc is still 0.3.0

**Comment by Wakamu** [comment] 2021-04-14 16:53
I changed the Mapping and the game version correctly, but whenever i build i get an error that GenerateReferences failed and a huge list of repeating errors, mainly :
`Reactor.OxygenFilter.MSBuild.props(37,9): error MSB4018: System.AggregateException: One or more errors occurred. (Arithmetic operation resulted in an overflow.)`

**Comment by fatalterreur** [comment] 2021-04-15 00:06
I have the same problem

**Comment by MrFawkes1337** [comment] 2021-04-15 01:13
If you followed the guide at http://docs.reactor.gg open a command prompt window by pressing shift + right click on the folder containing TownOfUs.csproj and execute dotnet build, which will fix the initial errors with Reactor. After that, you need to update the project.

**Comment by Wakamu** [comment] 2021-04-15 01:52
The error i'm talking about is happening WHEN i do the dotnet build in the command prompt.

**Comment by MrFawkes1337** [comment] 2021-04-15 04:20
If that’s the issue, you didn’t update the project correctly. I have just downloaded the source code provided, edited the .csproj to use the 0.4.0 Mappings with 2021.4.12s and once I updated everything else it again builds fine. You still need to update any manual mappings, as well as fix the Text errors caused by Among Us Removing TextRenderer, and it builds fine.

**Comment by Wakamu** [comment] 2021-04-15 07:34
I made sure my among us game was updated to 2021.4.12s , installed the latest bepinex build from Nuclear and the latest Reactor version , checked that it works correctly by launching the game and it does work.
I made sure my AmongUs env var was correctly set up ( it already was since i could build town of us successfully before the latest update).
I downloaded the whole project untouched ,  edited the csproj by changing the mapping version to 0.4.0 and game version to 2021.4.12s.
Then i open a command prompt in the folder the csproj is and do dotnet build and i get the exact error i posted earlier...

**Comment by MrFawkes1337** [comment] 2021-04-15 12:06
> I made sure my among us game was updated to 2021.4.12s , installed the latest bepinex build from Nuclear and the latest Reactor version , checked that it works correctly by launching the game and it does work.
> I made sure my AmongUs env var was correctly set up ( it already was since i could build town of us successfully before the latest update).
> I downloaded the whole project untouched , edited the csproj by changing the mapping version to 0.4.0 and game version to 2021.4.12s.
> Then i open a command prompt in the folder the csproj is and do dotnet build and i get the exact error i posted earlier...

In that case, this is a weird issue I cannot replicate, you might wanna contact Reactor Devs, as OxygenFilter is nothing to do with Town of Us.

**Comment by KaiKikuchi** [comment] 2021-04-21 15:27
Hey @fatalterreur I had the same issue.

Are you sure your game wasn't updated to 2021.4.14?

I fixed it by following this: https://github.com/NuclearPowered/Reactor/issues/29#issuecomment-822761268

**Comment by Wakamu** [comment] 2021-04-21 20:05
After lots of test i finaly fixed by making sure i'm using the 64b version of the dotnet sdk, if the build uses the x86 one it gives that error

**Closed** 2021-06-26 01:17 UTC
