### ISSUE TITLE
Roles issues

### ISSUE THREAD

**Issue by Andrzejone** [polusgg/Town-Of-Us#2] opened 2021-02-24 17:46 UTC
Some Roles ain't working.
The Swapper is bugged. Can't hange votes or vote himself.
The Mayor, on 2th meeting, when on 1st he used all votes, he have -1 vote also, when with his votes the resul of meeting will be tie, there won't be a tie, ex. two votes on #5 player and two Mayor votes on another player + one skip or another player. Player #5 is voted out.
The Engineer not always have the button to fix sabotages. If on game start he don't have, he won't have on entire game

**Comment by Andrzejone** [comment] 2021-02-24 17:54
Also sometimes it's bugged and showind on emergensy button that all of players are engineer, so they can't call emergensy.

**Comment by slushiegoose** [comment] 2021-02-25 06:56
> The Swapper is bugged. Can't hange votes or vote himself.

is this always? or just sometimes?

>The Mayor, on 2th meeting, when on 1st he used all votes, he have -1 vote also, when with his votes the resul of meeting will be tie, there won't be a tie, ex. two votes on #5 player and two Mayor votes on another player + one skip or another player. Player #5 is voted out.

This should be fixed for the next update!

> The Engineer not always have the button to fix sabotages. If on game start he don't have, he won't have on entire game

Is this often or did this only happen once? The way the button should work is that he can fix once per round and then the button disappears - is it working differently?

> Also sometimes it's bugged and showind on emergensy button that all of players are engineer, so they can't call emergency.

Once the Engineer has used their fix, *nobody* is allowed to push the button - I might clarify that in the roles but if it seems unbalanced I'll change it so that it's only the Engineer

**Comment by slushiegoose** [comment] 2021-02-25 07:51
> > The Swapper is bugged. Can't hange votes or vote himself.

> is this always? or just sometimes?

Wait I found the problem - fixed it for the next update

**Comment by slushiegoose** [comment] 2021-02-25 12:00
Swapper & Mayor fixed in v1.0.2

**Comment by Andrzejone** [comment] 2021-02-25 14:23
The Engineer not always have the button to fix sabotages. If on game start he don't have, he won't have on entire game

Is this often or did this only happen once? The way the button should work is that he can fix once per round and then the button disappears - is it working differently?

Happened more times. I didn't check new version, gonna see if it still occurs.

**Comment by TomKyrre** [comment] 2021-02-27 13:41
Nice mod!

Did a test game in 1.03 version. Investigator, Shifter, Time Master, Major did work as intended. Didn't test all roles.

Bug: Engineer role was unable to fix sabotages from anywhere during 3 test games. When the engineer did fix the sabotage himself as a normal crewmate would, his position was exposed by the imposter (This feature works as described).

**Closed** 2021-06-26 01:07 UTC
